# Generated by Django 4.0.1 on 2022-02-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210522_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Jobs', 'Jobs'), ('Books&Sports', 'Books&Sports'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Cars', 'Cars'), ('Mobiles', 'Mobiles'), ('Property', 'Property'), ('Electronics', 'Electronics'), ('Bikes', 'Bikes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('KA', 'Karnataka'), ('CG', 'Chhattisgarh'), ('ML', 'Meghalaya'), ('BR', 'Bihar'), ('MI', 'Sikkim'), ('MZ', 'Mizoram'), ('AP', 'Andhra Pradesh'), ('MP', 'Madhya Pradesh'), ('UP', 'Uttar Pradesh'), ('HP', 'Haryana'), ('KL', 'Kerala'), ('TR', 'Tripura'), ('PB', 'Punjab'), ('AR', 'Arunachal Pradesh'), ('MH', 'Maharashtra'), ('NL', 'Nagaland'), ('WB', 'West Bengal'), ('JH', 'Jharkhand'), ('TS', 'Telegana'), ('GA', 'Goa'), ('RJ', 'Rajasthan'), ('UK', 'Uttarakhand'), ('TN', 'Tamil Nadu'), ('OD', 'Odisha'), ('MN', 'Manipur'), ('GJ', 'Gujarat'), ('AS', 'Assam')], max_length=100),
        ),
    ]
