# Generated by Django 4.0.1 on 2022-03-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture'), ('Jobs', 'Jobs'), ('Cars', 'Cars'), ('Books&Sports', 'Books&Sports'), ('Bikes', 'Bikes'), ('Electronics', 'Electronics'), ('Property', 'Property')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('RJ', 'Rajasthan'), ('AS', 'Assam'), ('MH', 'Maharashtra'), ('AR', 'Arunachal Pradesh'), ('MP', 'Madhya Pradesh'), ('OD', 'Odisha'), ('CG', 'Chhattisgarh'), ('KL', 'Kerala'), ('WB', 'West Bengal'), ('KA', 'Karnataka'), ('UP', 'Uttar Pradesh'), ('MN', 'Manipur'), ('UK', 'Uttarakhand'), ('GA', 'Goa'), ('JH', 'Jharkhand'), ('MI', 'Sikkim'), ('TS', 'Telegana'), ('HP', 'Haryana'), ('TR', 'Tripura'), ('NL', 'Nagaland'), ('TN', 'Tamil Nadu'), ('GJ', 'Gujarat'), ('ML', 'Meghalaya'), ('BR', 'Bihar'), ('AP', 'Andhra Pradesh'), ('PB', 'Punjab'), ('MZ', 'Mizoram')], max_length=100),
        ),
    ]
