# Generated by Django 4.0.1 on 2022-03-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Bikes', 'Bikes'), ('Furniture', 'Furniture'), ('Property', 'Property'), ('Fashion', 'Fashion'), ('Books&Sports', 'Books&Sports'), ('Cars', 'Cars'), ('Jobs', 'Jobs'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MZ', 'Mizoram'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('UK', 'Uttarakhand'), ('TS', 'Telegana'), ('GA', 'Goa'), ('MP', 'Madhya Pradesh'), ('GJ', 'Gujarat'), ('MN', 'Manipur'), ('RJ', 'Rajasthan'), ('WB', 'West Bengal'), ('AR', 'Arunachal Pradesh'), ('MH', 'Maharashtra'), ('NL', 'Nagaland'), ('KL', 'Kerala'), ('AP', 'Andhra Pradesh'), ('CG', 'Chhattisgarh'), ('PB', 'Punjab'), ('ML', 'Meghalaya'), ('TR', 'Tripura'), ('HP', 'Haryana'), ('OD', 'Odisha'), ('UP', 'Uttar Pradesh'), ('BR', 'Bihar'), ('JH', 'Jharkhand'), ('AS', 'Assam'), ('MI', 'Sikkim')], max_length=100),
        ),
    ]
