# Generated by Django 4.0.1 on 2022-03-25 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 26, 2, 39, 16, 829331)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Cars', 'Cars'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Electronics', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('CG', 'Chhattisgarh'), ('KL', 'Kerala'), ('MH', 'Maharashtra'), ('TN', 'Tamil Nadu'), ('OD', 'Odisha'), ('HP', 'Haryana'), ('WB', 'West Bengal'), ('JH', 'Jharkhand'), ('TS', 'Telegana'), ('GA', 'Goa'), ('MZ', 'Mizoram'), ('AR', 'Arunachal Pradesh'), ('ML', 'Meghalaya'), ('MN', 'Manipur'), ('NL', 'Nagaland'), ('TR', 'Tripura'), ('AP', 'Andhra Pradesh'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('BR', 'Bihar'), ('KA', 'Karnataka'), ('MI', 'Sikkim'), ('AS', 'Assam'), ('GJ', 'Gujarat'), ('PB', 'Punjab'), ('MP', 'Madhya Pradesh'), ('RJ', 'Rajasthan')], max_length=100),
        ),
    ]
