# Generated by Django 4.0.1 on 2022-03-25 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_post_date_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Bikes', 'Bikes'), ('Electronics', 'Electronics'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 26, 3, 36, 0, 144604)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('ML', 'Meghalaya'), ('JH', 'Jharkhand'), ('CG', 'Chhattisgarh'), ('AS', 'Assam'), ('NL', 'Nagaland'), ('AR', 'Arunachal Pradesh'), ('GJ', 'Gujarat'), ('MZ', 'Mizoram'), ('WB', 'West Bengal'), ('OD', 'Odisha'), ('KL', 'Kerala'), ('KA', 'Karnataka'), ('MH', 'Maharashtra'), ('MP', 'Madhya Pradesh'), ('HP', 'Haryana'), ('UP', 'Uttar Pradesh'), ('BR', 'Bihar'), ('RJ', 'Rajasthan'), ('MI', 'Sikkim'), ('AP', 'Andhra Pradesh'), ('MN', 'Manipur'), ('TS', 'Telegana'), ('TN', 'Tamil Nadu'), ('TR', 'Tripura'), ('UK', 'Uttarakhand'), ('GA', 'Goa'), ('PB', 'Punjab')], max_length=100),
        ),
    ]
