# Generated by Django 4.0.1 on 2022-03-25 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_category_alter_listing_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Property', 'Property'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Bikes', 'Bikes'), ('Mobiles', 'Mobiles'), ('Jobs', 'Jobs'), ('Furniture', 'Furniture'), ('Cars', 'Cars'), ('Books&Sports', 'Books&Sports')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 26, 3, 37, 42, 145897)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MI', 'Sikkim'), ('TS', 'Telegana'), ('KA', 'Karnataka'), ('GJ', 'Gujarat'), ('UP', 'Uttar Pradesh'), ('TN', 'Tamil Nadu'), ('AS', 'Assam'), ('MP', 'Madhya Pradesh'), ('GA', 'Goa'), ('NL', 'Nagaland'), ('UK', 'Uttarakhand'), ('TR', 'Tripura'), ('AR', 'Arunachal Pradesh'), ('MZ', 'Mizoram'), ('OD', 'Odisha'), ('CG', 'Chhattisgarh'), ('PB', 'Punjab'), ('AP', 'Andhra Pradesh'), ('JH', 'Jharkhand'), ('MN', 'Manipur'), ('RJ', 'Rajasthan'), ('ML', 'Meghalaya'), ('WB', 'West Bengal'), ('MH', 'Maharashtra'), ('BR', 'Bihar'), ('KL', 'Kerala'), ('HP', 'Haryana')], max_length=100),
        ),
    ]
